### ISSUE TITLE
升级后饼干，收藏数据丢失

### ISSUE THREAD

**Issue by doublemoyu** [tiamed/bog-nimingban#11]
alpha.6升级至alpha.7版本后，丢失了饼干数据和收藏数据
虽然目前收藏不多，不是什么大事，但后面用久了如果丢失的话会很麻烦
建议添加备份功能

**Comment by doublemoyu** [comment]
原来alpha.7是跟原来的alpha.6变成两个软件不是普通升级
没有丢失，数据在原来的软件里

**Comment by tiamed** [comment]
@doublemoyu 改包名了

**Comment by tiamed** [comment]
已增加备份功能
