### ISSUE TITLE
提几个个人感受

### ISSUE THREAD

**Issue by jcn-wind** [tiamed/bog-nimingban#2]
回复后不会刷新页面

以及中间放翻页按钮会不会好一些

签到会报错

经常意外点开图片

串跳转的实现方式导致内容特别多的串被显示时，整个屏幕被占据，跳转按钮找不到了

**Comment by jcn-wind** [comment]
还有 串标题 和 名称 没有显示，这里可能会被用来整活，不显示挺可惜的

**Comment by jcn-wind** [comment]
每次点击都会闪一下，希望去掉这个效果

**Comment by jcn-wind** [comment]
导入主饼干不会同步影武者

超长文本省略，在版面上只显示前5行就好

**Comment by tiamed** [comment]
> 导入主饼干不会同步影武者
> 
> 超长文本省略，在版面上只显示前5行就好

影武者相关功能未实现，版面显示已限制至10行
