### ISSUE TITLE
主页面列表图片查看反馈

### ISSUE THREAD

**Issue by doublemoyu** [tiamed/bog-nimingban#4]
![IMG_20220331_085153](https://user-images.githubusercontent.com/98216523/160954836-8f1ad4b6-3c43-496d-9262-b8f1173d51ca.jpg)
整个红色框选区点击都会查看图片，但图片本身有又没有那么长，有些违反逻辑，靠在右边又是大多数人点击更顺手的地方，或许可以把空白区域不和图片点击相关联，实现有困难可以把图片放在左边，但治标不治本

**Comment by tiamed** [comment]
串外已限制展示10行
