### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by jcn-wind** [tiamed/bog-nimingban#5]
导入饼干没有同步导入影武者

无法复制饼干代码

希望能把引用展示方式改为内容展开

**Comment by jcn-wind** [comment]
串内触摸楼层会使得楼层出现闪烁效果，希望去除

**Comment by jcn-wind** [comment]
希望把分享按钮放在第一位，因为用不太上，中间的按钮点起来舒服些

**Comment by tiamed** [comment]
> 希望把分享按钮放在第一位，因为用不太上，中间的按钮点起来舒服些

使用习惯这个比较私人，暂时不会改

**Comment by tiamed** [comment]
v1.0.0-alpha.24已支持
