### ISSUE TITLE
回复框内文字选取bug

### ISSUE THREAD

**Issue by doublemoyu** [tiamed/bog-nimingban#9]
![Screenshot_2022-04-01-02-12-13-571_ac.bog.jpg](https://user-images.githubusercontent.com/98216523/161123391-7b40a2e2-4cff-44d0-a9ba-d7f4301e2e1b.jpg)
如图，在回复框内输入文字后会无法选取调用复制菜单，而且光标会疯狂闪烁

**Comment by doublemoyu** [comment]
已复现：使用无发图权限的饼干发送有图片的回复后，再弹出提示内容后会出现发送框内文字无法选中的情况

**Comment by tiamed** [comment]
未能复现，请提供下型号及系统版本、软件版本，安装最新版本再试试

**Comment by doublemoyu** [comment]
重新试着复现了一下，似乎和发图没有必然联系，再内容输入框内，长按选中后大概率无法弹出复制菜单
推测可能是和miui深度魔改的长按菜单有关，之前在tg上也有类似情况，长按只能呼出系统自带的复制菜单，无法使用软件提供的加粗，斜体等功能
软件版本：alpha.2/alpha.3
设备型号：红米k30ultra/M2006J10C
系统版本：miui12.5.11稳定版
安卓版本：11

**Comment by doublemoyu** [comment]
![Screenshot_2022-04-01-10-39-14-936_ac.bog.jpg](https://user-images.githubusercontent.com/98216523/161184463-0b9cba6e-3928-4b71-833a-a035686d248a.jpg)
目前长按选中后是这样，没有两侧的选取光标和应该弹出的复制菜单

**Comment by tiamed** [comment]
需要选中后再次长按

**Comment by tiamed** [comment]
alpha.4复现了，看到一个类似的[case](https://github.com/Expensify/App/issues/6876)
